### ISSUE TITLE
Updating to persistgraphql 0.4.0 should have been a minor version

### ISSUE THREAD

**Issue by sam-breed-ck** [sysgears/persistgraphql-webpack-plugin#13]
This currently breaks npm installs because of upstream issues with persistgraphql mishandling `bin`.

Either way, releasing this without bumping the minor version is causing the dep to be auto updated. I suggest pinning it to the previous version and making a patch release (v0.3.4) and then bumping to v0.4.0 for the updated `persistgraphql` dependency.

**Comment by larixer** [comment]
@sam-breed-ck `persistgraphql-webpack-plugin@0.3.5` now uses `persistgraphql@0.3.1` and `persistgraphql-webpack-plugin@0.4.1` uses `persistgraphql@0.4.0`

Hope this helps. Please reopen if face issues with this

**Comment by sam-breed-ck** [comment]
Thanks for the quick updates! I'll try this out today and let you know if
I'm still seeing errors

**Comment by qgustavor** [comment]
The latest version of [persistgraphql](https://www.npmjs.com/package/persistgraphql) is 0.3.5. If you see the list of versions in `npm info persistgraphql` it upgrades from 0.3.2 to 0.4.0 then downgrades to 0.3.3. I couldn't find in commit history why it happened but seems it was a mistake when doing `npm version` command.

Note that [the version 0.3.5 includes the bin folder](https://unpkg.com/persistgraphql@0.3.5/) and [the version 0.4.0 doesn't](https://unpkg.com/persistgraphql@0.4.0/), probably because [this issue](https://github.com/apollographql/persistgraphql/issues/40), which makes the installation fail. Changing the version of persistgraphql in package.json should fix this issue.

**Comment by larixer** [comment]
@qgustavor @sam-breed-ck I have published persistgraphql-webpack-plugin@0.4.2, which uses persistgraphql@^0.3.5
